language: node_js
node_js:
  - 8
  - 10
  - latest
  - stable

git:
  depth: false

branches:
  only:
    - travis-test

matrix:
  include:
    - node_js: 8

    - node_js: 10

    - node_js: latest

    - node_js: stable

script: skip

